version: "3.9"

services:
  crypto-etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-etl
    volumes:
      - ./secrets:/app/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/projeto-estudando-gcp-4617dc946a75.json
    command: python main.py
